### ISSUE TITLE
Working sample

### ISSUE THREAD

**Issue by azell** [walkmod/walkmod-java-formatter-plugin#3]
Would it be possible to post a minimal Java project using the plugin?  I have tried running the plugin with different versions of walkmod.xml but the formatter does not change any files.

```
<!DOCTYPE walkmod PUBLIC "-//WALKMOD//DTD"  "http://www.walkmod.com/dtd/walkmod-1.0.dtd" >
<walkmod>
  <plugins>
    <plugin groupId="org.walkmod" artifactId="walkmod-java-formatter-plugin" version="2.3.0" />
  </plugins>
  <chain name="example-chain" >
    <reader path="src" />
    <transformation type="walkmod:commons:eclipse-formatter" />
    <writer path="src" />
  </chain>
</walkmod>
```

```
DEBUG [main] - Walkmod configuration parsed
 INFO [main] - Loading XML bean definitions from class path resource [application-context.xml]
 INFO [main] - Loading XML bean definitions from class path resource [META-INF/walkmod/walkmod-java-formatter-plugin.xml]
 INFO [main] - Loading XML bean definitions from class path resource [META-INF/walkmod/walkmod-javalang-plugin.xml]
 INFO [main] - Loading XML bean definitions from class path resource [META-INF/walkmod/walkmod-java-formatter-plugin.xml]
 INFO [main] - Overriding bean definition for bean 'org.walkmod:walkmod-java-formatter-plugin:writer': replacing [Generic bean: class [org.walkmod.javaformatter.writers.EclipseWriter]; scope=prototype; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null; defined in class path resource [META-INF/walkmod/walkmod-java-formatter-plugin.xml]] with [Generic bean: class [org.walkmod.javaformatter.writers.EclipseWriter]; scope=prototype; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null; defined in class path resource [META-INF/walkmod/walkmod-java-formatter-plugin.xml]]
 INFO [main] - Refreshing org.springframework.context.support.GenericApplicationContext@12c8a2c0: startup date [Tue Sep 08 20:31:54 PDT 2015]; root of context hierarchy
 INFO [main] - Pre-instantiating singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@75329a49: defining beans [walkmod:commons:file-reader,walkmod:commons:template,walkmod:commons:scripting,walkmod:commons:groovy-query-engine,walkmod:commons:groovy,walkmod:commons:unmodify-policy,walkmod:commons:append-policy,walkmod:commons:assign-policy,walkmod:commons:addall-policy,walkmod:commons:override-policy,org.walkmod:walkmod-java-formatter-plugin:writer,walkmod:commons:field-policy,walkmod:commons:comment-policy,org.walkmod:walkmod-javalang-plugin:walker,org.walkmod:walkmod-javalang-plugin:parser,org.walkmod:walkmod-javalang-plugin:string-writer,org.walkmod:walkmod-javalang-plugin:field-policy]; root of factory hierarchy
 INFO [main] - ** STARTING TRANSFORMATIONS CHAINS **
--------------------------------------------------------------------------------
DEBUG [main] - Chain example-chain found
DEBUG [main] - Model src loaded
DEBUG [main] - setting chain["example-chain"].transformation["walkmod:commons:eclipse-formatter"].walker = org.walkmod.javalang.walkers.DefaultJavaWalker
DEBUG [main] - setting chain["example-chain"].transformation["walkmod:commons:eclipse-formatter"].visitor = org.walkmod.javaformatter.writers.EclipseWriter
DEBUG [main] - src/main/java/com/foo/App.java [ visiting ]
DEBUG [main] - src/main/java/com/foo/App.java [ visited ]
DEBUG [main] - src/test/java/com/foo/AppTest.java [ visiting ]
DEBUG [main] - src/test/java/com/foo/AppTest.java [ visited ]
DEBUG [main] - The transformation [walkmod:commons:eclipse-formatter] has been executed
 INFO [main] - **No sources changed**

 INFO [main] - TRANSFORMATION CHAIN SUCCESS
--------------------------------------------------------------------------------
```

**Comment by rpau** [comment]
Hi Adam,

The eclipse formatter is not a code transformation,  is just a writer. In fact, the eclipse formatter it is the default writer and you don't need to include it as a plugin. 

For another hand, by default, walkmod just writes those files that has been modified by at least one transformation (component that changes the structure of the code syntax or semantics, not just its style "css" ).

So, you need to select one transformation of the available plugins (override, imports-cleaner, license adder, refactoring, dead-code-cleaner) that can add / delete parts in your code (eg. imports cleaner) and also set in the walker configuration, that you always want to execute the writer. Look into its github web page to learn how to use them.

So, here it is one configuration example that I suggest you that works for me. When you run walkmod with this config, all your code base will be rewritten, but the standard output will notify (anyway) just those files that has been affected by the import cleaner.
----
<!DOCTYPE walkmod PUBLIC "-//WALKMOD//DTD"  "http://www.walkmod.com/dtd/walkmod-1.0.dtd" >
<walkmod>
  <plugins>
    <plugin groupId="org.walkmod" artifactId="walkmod-imports-cleaner-plugin" version="[2.0,)" />
  </plugins>
  <chain name="example-chain" >
    <reader path="src" />
    <walker>
        <param name="onlyWriteChanges">false</param>
        <transformations>
        	<transformation type="walkmod:commons:import-cleaner" />
        </transformations>
    </walker>
    <writer path="src" />
  </chain>
</walkmod>
----
If you want to specify your own eclipse formatter options, you need to add a param element inside the writter called "configFile" with the path of your options (relative to the root directory of your project).

----
  <writer path="src" >
    <param name="configFile">myconfig.xml</param>
  </writer>
----

Probably, the webpage needs more explanation about it. I will write ASAP, but I am working in other issues. So, if you would like to contribute, please, feel free to apply a pull request with the README file updated :-)

Thanks!

**Comment by pkmusthafa** [comment]
Hi, 
Would it be possible to restrict the default formating of the file and implement only the dead-code-cleaner,imports cleaner etc.?

**Comment by pechorinn** [comment]
Hi guys,
I'm trying to format code using myconfig.xml extracted from Eclipse but it seems walkmod is unimpressed and formats it the way it usually does. Do you have any ideas what might be the issue?
Thanks.

**Comment by rpau** [comment]
@pechorinn could you share your `walkmod.xml` with a GitHub gist?
I am creating a repo with several examples. Let me create one for the formatter.

**Comment by pechorinn** [comment]
@rpau Thank you for prompt response. I was experimenting a lot. Below is one version. I'm surprised how little information is available on the net about the issue [](url)https://gist.github.com/pechorinn/1ee9579e368874fc51a63e81b1fdf5a9

**Comment by pechorinn** [comment]
I run <transformation type="walkmod:commons:import-cleaner" /> without any issues, still provided format is not being used though , however,  when adding <transformation type="sonar:RemoveUselessVariables"/> to the chain below error appears. Did anyone come across such issue?  [](url)src="https://gist.github.com/pechorinn/f4a493ac3e1e560b059c25a877864f72
